# Generated by Django 3.2.25 on 2025-03-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default=1, upload_to='hotels/'),
            preserve_default=False,
        ),
    ]
