# Generated by Django 3.2.25 on 2025-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_hotel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_per_night',
            new_name='price',
        ),
        migrations.AddField(
            model_name='room',
            name='room_plan',
            field=models.ImageField(default=True, upload_to='plan/'),
            preserve_default=False,
        ),
    ]
