# Generated by Django 3.2.25 on 2025-03-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20250313_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='media/hotels/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_plan',
            field=models.ImageField(upload_to='media/plan/'),
        ),
    ]
