# Generated by Django 3.2.25 on 2025-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20250313_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='distric',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='mandal',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
