# Generated by Django 3.2.25 on 2025-03-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20250313_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='price_per_night',
        ),
    ]
