# Generated by Django 3.2.25 on 2025-03-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_rename_price_room_price_per_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellation',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_by',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20),
        ),
        migrations.DeleteModel(
            name='BookingAnalytics',
        ),
        migrations.DeleteModel(
            name='Cancellation',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
