# Generated by Django 3.2.25 on 2025-03-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20250313_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancel_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
